from typing import List
from ..state import Company, InvestmentCriteria


# Base mock: following the "Sample Mock Data Structure" (data generated by ChatGPT)
_MOCK_COMPANIES: List[Company] = [
    {
        "company_name": "TechCorp GmbH",
        "industry": "SaaS",
        "geography": "Germany",
        "revenue_eur": 25_000_000,
        "revenue_growth_3yr": 0.35,
        "ebitda_margin": 0.22,
        "employee_count": 150,
        "founded_year": 2015,
        "debt_to_equity": 0.30,
        "market_position": "Regional leader in HR tech",
    },
    {
        "company_name": "CloudWorks AG",
        "industry": "SaaS",
        "geography": "Germany",
        "revenue_eur": 55_000_000,
        "revenue_growth_3yr": 0.08,
        "ebitda_margin": 0.14,
        "employee_count": 320,
        "founded_year": 2012,
        "debt_to_equity": 1.10,
        "market_position": "Mature ERP cloud suite for mid-market",
    },
    {
        "company_name": "FinPulse Ltd",
        "industry": "Fintech",
        "geography": "UK",
        "revenue_eur": 18_000_000,
        "revenue_growth_3yr": 0.42,
        "ebitda_margin": 0.19,
        "employee_count": 120,
        "founded_year": 2018,
        "debt_to_equity": 0.25,
        "market_position": "Fast-growing payments platform",
    },
    {
        "company_name": "RetailStack GmbH",
        "industry": "Retail",
        "geography": "Germany",
        "revenue_eur": 30_000_000,
        "revenue_growth_3yr": -0.05,
        "ebitda_margin": 0.07,
        "employee_count": 220,
        "founded_year": 2010,
        "debt_to_equity": 0.85,
        "market_position": "Niche POS provider under price pressure",
    },
]


def mock_company_search(criteria: InvestmentCriteria) -> List[Company]:
    """
    Mock de búsqueda: filtra sobre _MOCK_COMPANIES usando criteria.
    - industry: match exacto si está presente
    - geography: match exacto si está presente
    - revenue_range_eur: filtra por rango si está presente
    """
    industry = criteria.get("industry")
    geography = criteria.get("geography")
    rev_range = criteria.get("revenue_range_eur")

    results: List[Company] = []
    for c in _MOCK_COMPANIES:
        if industry and c["industry"] != industry:
            continue
        if geography and c["geography"] != geography:
            continue
        if rev_range:
            rmin, rmax = rev_range
            if not (rmin <= c["revenue_eur"] <= rmax):
                continue
        results.append(c)

    return results
